const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim T-Shirt',
            slug:'nike-slim-shirt',
            category:'T-Shirts',
            image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_j2__v1i7ZFKA7H_mUW_d_hKp2c00kdwPWg&usqp=CAU',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'High quality t-shirt',
        },
        {
            _id:'2',
            name:'Adidas T-Shirt',
            slug:'adidas-t-shirt',
            category:'Adidas T-Shirts',
            image:'https://m.media-amazon.com/images/I/81vNU4ZfpHL._UY550_.jpg',
            price:120,
            countInStock:0,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'High quality t-shirt',
        },
        {
            _id:'3',
            name:'Collared Shirt',
            slug:'collared-shirt',
            category:'Shirts',
            image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzeKMTl-p1TdgieMtRHu9mHydRm9fmW39f-w&usqp=CAU',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'High quality shirt',
        },
        {
            _id:'4',
            name:'H&M Trousers',
            slug:'trousers',
            category:'Trousers',
            image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVAOu27hIjh26fQYNimM52OtbfvslbIkExYQ&usqp=CAU',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'High quality fabric',
        },
    ],
};
export default data;